= Turing Computer Yocto BSP (Jethro)

Quick Start Guide
-----------------

Once you have downloaded the source of all projects, you will have to
call:

$: . ./setup-environment <build directory>

After this step, you will be with everything need for build an image.

The following layers are included on this release:

[source,console]
poky: base build system and metadata
Path: sources/poky
GIT: git://git.yoctoproject.org/poky

[source,console]
meta-openembedded: extra packages and features
Path: sources/meta-openembedded
GIT: git://git.openembedded.org/meta-openembedded

[source,console]
meta-fsl-arm: support for Freescale's processors and board
Path: sources/meta-fsl-arm
Project: https://github.com/Freescale/meta-fsl-arm
GIT: git://github.com/Freescale/meta-fsl-arm.git

[source,console]
meta-fsl-arm: support for Freescale's processors and board
Path: sources/meta-fsl-arm
Project: https://github.com/Freescale/meta-fsl-arm
GIT: git://github.com/Freescale/meta-fsl-arm.git

[source,console]
meta-fsl-arm-extra: support for boards using Freescale's processors
Path: sources/meta-fsl-arm-extra
Project: https://github.com/Freescale/meta-fsl-arm-extra
GIT: git://github.com/Freescale/meta-fsl-extra.git

[source,console]
meta-fsl-demos: demo images and recipes
Path: sources/meta-fsl-demos
Project: https://github.com/Freescale/meta-fsl-demos
GIT: git://github.com/Freescale/meta-fsl-demos.git

[source,console]
meta-turing: support for Turing machines, images and recipes
Path: sources/meta-turing
Project: https://github.com/TuringComputer/meta-turing
GIT: git://github.com/TuringComputer/meta-turing.git

[source,console]
meta-qt5: support for QT5
Path: sources/meta-qt5
Project: https://github.com/meta-qt5
GIT: git://github.com/meta-qt5

[source,console]
meta-browser: support for Firefox and Chromium Browsers
Path: sources/meta-browser
Project: https://github.com/OSSystems/meta-browser
GIT: git://github.com/OSSystems/meta-browser
